import { RollTier, TeamMember, ViewfinderScene } from "@/types";

export const ROLL_TIERS: RollTier[] = [
  {
    exposures: 4,
    name: "The Moment",
    badge: "4 EXP • MICRO ROLL",
    subtitle: "15-Minute Spontaneous Catchup",
    description:
      "Engineered for quick coffee dates, golden hour walks, and single-location moments where 24 shots is overkill.",
    idealFor: "Coffee runs, sunsets, rooftop drinks",
    duration: "15-30 Mins",
    canisterCode: "EMU-04-MOMENT",
    colorAccent: "#C86428",
  },
  {
    exposures: 8,
    name: "The Evening",
    badge: "8 EXP • DINNER ROLL",
    subtitle: "Intimate Dinner & Night Stroll",
    description:
      "The perfect size for an evening out with friends. Enough frames to capture the atmosphere without anyone getting glued to a screen.",
    idealFor: "Dinner parties, jazz bars, concert nights",
    duration: "2-4 Hours",
    canisterCode: "EMU-08-EVENING",
    colorAccent: "#A73812",
  },
  {
    exposures: 12,
    name: "The Weekend",
    badge: "12 EXP • SWAP TIER",
    subtitle: "2-Person Roll Swap / Road Trip",
    description:
      "Our most popular shared roll. 6 shots for you, 6 shots for your best friend. Shoot blind together, develop simultaneously.",
    idealFor: "Weekend getaways, 2-person Roll Swaps, day trips",
    duration: "2-3 Days",
    canisterCode: "EMU-12-WEEKEND",
    colorAccent: "#C5A870",
  },
  {
    exposures: 16,
    name: "The Story",
    badge: "16 EXP • EVENT ROLL",
    subtitle: "Festivals & Multi-Day Celebrations",
    description:
      "A cinematic chapter. Ideal for weddings, music festivals, or holiday trips where every frame should count as an heirloom.",
    idealFor: "Music festivals, birthday trips, celebrations",
    duration: "4-7 Days",
    canisterCode: "EMU-16-STORY",
    colorAccent: "#9E7D3B",
  },
  {
    exposures: 24,
    name: "The Classic 35mm",
    badge: "24 EXP • FULL ARCHIVE",
    subtitle: "Full Month Archival Chronicle",
    description:
      "The legendary full 35mm cartridge. Carry it across a month, take 1 intentional shot a day, and experience the ultimate delayed gratification.",
    idealFor: "Monthly archive, solo travel, deep memories",
    duration: "3-4 Weeks",
    canisterCode: "EMU-24-CLASSIC",
    colorAccent: "#1A1815",
  },
];

export const TEAM_MEMBERS: TeamMember[] = [
  {
    name: "Mohammed Hamza",
    role: "Founder & CEO",
    focus: "Product vision, systems architecture, and core execution.",
    bio: "Obsessed with mechanical analog cameras and tactile interfaces. Built EMULSION to free our shared memories from the endless dopamine loop of social metrics.",
    favoriteStock: "Kodak Portra 400",
    iso: "ISO 400",
    location: "San Francisco / London",
    handle: "hamza",
    avatarSeed: "hamza",
  },
  {
    name: "Aditir Jana",
    role: "Head of Creative & Research",
    focus: "User research, film aesthetics, and tactile UX design.",
    bio: "Archival photographer and visual researcher specializing in analog color science, LUT color mapping, and nostalgic sensory feedback.",
    favoriteStock: "CineStill 800T",
    iso: "ISO 800",
    location: "New York / Berlin",
    handle: "aditir",
    avatarSeed: "aditir",
  },
  {
    name: "Vinay",
    role: "Head of Marketing & Brand Outreach",
    focus: "Viral growth loops, marketing campaigns, and partnerships.",
    bio: "Growth architect fascinated by underground culture, darkroom pop-ups, and building genuine community movements over paid ads.",
    favoriteStock: "Ilford HP5 Plus",
    iso: "ISO 400 B&W",
    location: "Tokyo / Mumbai",
    handle: "vinay",
    avatarSeed: "vinay",
  },
  {
    name: "Hiransh Ameta",
    role: "Founding Member & Community Experience",
    focus: "Early access testing, user feedback, and culture grounding.",
    bio: "Leads our 1,000 founding member cohort, alpha testing live roll swaps, hosting physical gallery exhibitions, and ensuring real human connection.",
    favoriteStock: "Kodak Tri-X 400",
    iso: "ISO 400 Grain",
    location: "Toronto / Dubai",
    handle: "hiransh",
    avatarSeed: "hiransh",
  },
];

export const VIEWFINDER_SCENES: ViewfinderScene[] = [
  {
    id: 1,
    title: "Morning Espresso & Paper",
    location: "Cafe Milano • 08:42 AM",
    iso: 400,
    aperture: "ƒ/2.8",
    shutter: "1/250s",
    filmStock: "PORTRA 400",
    imageUrl: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=1200&q=85",
    caption: "Stream of warm sunlight cut through the steam of a double espresso.",
    grainIntensity: 0.25,
  },
  {
    id: 2,
    title: "Golden Hour Rooftop",
    location: "Greenwich Village • 06:15 PM",
    iso: 400,
    aperture: "ƒ/4.0",
    shutter: "1/500s",
    filmStock: "GOLD 200",
    imageUrl: "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&w=1200&q=85",
    caption: "Laughter caught mid-conversation. No one asked for a retake.",
    grainIntensity: 0.35,
  },
  {
    id: 3,
    title: "Midnight Vinyl Session",
    location: "Studio 4B • 11:30 PM",
    iso: 800,
    aperture: "ƒ/1.8",
    shutter: "1/60s",
    filmStock: "CINESTILL 800T",
    imageUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=85",
    caption: "Halation rings on the tube amplifier. The complete roll is now sealed.",
    grainIntensity: 0.45,
  },
];
